export let bookList = {
  total: [
    {
      id: 0,
      bookName: "단어가 품은 세계",
      bookWriter: "황선엽",
      bookPoint: "인문 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank01.png",
      weekRank:4,
      monthRank:3,
    },
    {
      id: 1,
      bookName: "구해줘",
      bookWriter: "기욤 뮈소 지음 / 윤미연 옮김",
      bookPoint: "소설 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank02.png",
      weekRank:1,
      monthRank:0,
    },
    {
      id: 2,
      bookName: "애 같은 말투 10분 만에 바꿔 드립니다",
      bookWriter: "김채린",
      bookPoint: "자기계발 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank03.png",
      weekRank:3,
      monthRank:2,
    },
    {
      id: 3,
      bookName: "싯다르타",
      bookWriter: "헤르만 헤세 지음 / 박병덕 옮김",
      bookPoint: "소설 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank04.png",
      weekRank:2,
      monthRank:4,
    },
    {
      id: 4,
      bookName: "지적 대화를 위한 넓고 얕은 지식 무한",
      bookWriter: "채사장",
      bookPoint: "오디오북 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank05.png",
      weekRank:0,
      monthRank:1,
    },
  ],
  novel: [
    {
      id: 0,
      bookName: "파과",
      bookWriter: "구병모",
      bookPoint: "소설 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_novel01.png",
      weekRank:0,
      monthRank:0,
    },
    {
      id: 1,
      bookName: "폴링 인 폴",
      bookWriter: "백수련",
      bookPoint: "소설 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank_novel02.png",
      weekRank:2,
      monthRank:1,
    },
    {
      id: 2,
      bookName: "급류",
      bookWriter: "정대건",
      bookPoint: "소설 카테고리 주간 3위",
      imgSrc: "./images/books/bookrank_novel03.png",
      weekRank:1,
      monthRank:2,
    },
    {
      id: 3,
      bookName: "스토너",
      bookWriter: "존윌리엄스 지음, 김승옥 옮김",
      bookPoint: "소설 카테고리 주간 4위",
      imgSrc: "./images/books/bookrank_novel04.png",
      weekRank:4,
      monthRank:4,
    },
    {
      id: 4,
      bookName: "메스를 든 사냥꾼",
      bookWriter: "최이도",
      bookPoint: "소설 카테고리 주간 5위",
      imgSrc: "./images/books/bookrank_novel05.png",
      weekRank:3,
      monthRank:3,
    },
  ],
  economy: [
    {
      id: 0,
      bookName: "따박따박 경제상식 [ETF 첫걸음]",
      bookWriter: "밀리의서재 편집부",
      bookPoint: "따끈따끈 인기있는 신간을 확인해보세요",
      imgSrc: "./images/books/bookrank_economy01.png",
      weekRank:0,
      monthRank:1,
    },
    {
      id: 1,
      bookName: "단 3개의 미국 ETF로 은퇴하라",
      bookWriter: "김지훈(포메뽀꼬)",
      bookPoint: "경제경영 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_economy02.png",
      weekRank:2,
      monthRank:4,
    },
    {
      id: 2,
      bookName: "따박따박 경제상식 [ETF 실전]",
      bookWriter: "밀리의서재 편집부",
      bookPoint: "따끈따끈 인기있는 신간을 확인해보세요",
      imgSrc: "./images/books/bookrank_economy03.png",
      weekRank:1,
      monthRank:0,
    },
    {
      id: 3,
      bookName: "결핍은 우리를 어떻게 변화시키는가",
      bookWriter: "센딜 멀레이너선, 엘다 샤퍼 지음 / 이경식 옮김",
      bookPoint: "경제경영 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank_economy04.png",
      weekRank:3,
      monthRank:2,
    },
    {
      id: 4,
      bookName: "조용한 퇴사",
      bookWriter: "이호건",
      bookPoint: "경제경영 카테고리 주간 3위",
      imgSrc: "./images/books/bookrank_economy05.png",
      weekRank:4,
      monthRank:3,
    },
  ],
  self: [
    {
      id: 0,
      bookName: "생각하는 대로 그렇게 된다",
      bookWriter: "제임스 앨런",
      bookPoint: "오디오북 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_self01.png",
      weekRank:3,
      monthRank:2,
    },
    {
      id: 1,
      bookName: "업무시간을 반으로 줄이느 챗GPT 글쓰기",
      bookWriter: "정태일",
      bookPoint: "따끈따끈 인기있는 신간을 확인해보세요",
      imgSrc: "./images/books/bookrank_self02.png",
      weekRank:0,
      monthRank:3,
    },
    {
      id: 2,
      bookName: "호감 가는 사람은 말투가 다르다",
      bookWriter: "박근일",
      bookPoint: "자기계발 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_self03.png",
      weekRank:1,
      monthRank:0,
    },
    {
      id: 3,
      bookName: "살아갈 날들을 위한 괴테의 시",
      bookWriter: "김종원",
      bookPoint: "자기계발 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank_self04.png",
      weekRank:4,
      monthRank:1,
    },
    {
      id: 4,
      bookName: "사랑받는 이기주의자",
      bookWriter: "박코",
      bookPoint: "자기계발 카테고리 주간 3위",
      imgSrc: "./images/books/bookrank_self05.png",
      weekRank:3,
      monthRank:4,
    },
  ],
  poetry: [
    {
      id: 0,
      bookName: "고독한 미식가",
      bookWriter: "다니구치 지로 지음 / 구스미 마사유키 원작 / 박정임 옮김",
      bookPoint: "만화 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_poetry01.png",
      weekRank:2,
      monthRank:3,
    },
    {
      id: 1,
      bookName: "하늘을 봐, 바람이 불고 있어",
      bookWriter: "고윤(페이서스코리아)",
      bookPoint: "따끈따끈 인기있는 신간을 확인해보세요",
      imgSrc: "./images/books/bookrank_poetry02.png",
      weekRank:0,
      monthRank:0,
    },
    {
      id: 2,
      bookName: "어른의 행복은 조용하다",
      bookWriter: "태수",
      bookPoint: "시/에세이 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank_poetry03.png",
      weekRank:4,
      monthRank:2,
    },
    {
      id: 3,
      bookName: "사랑읭 정의는 고양이",
      bookWriter: "임현우",
      bookPoint: "시/에세이 카테고리 주간 3위",
      imgSrc: "./images/books/bookrank_poetry04.png",
      weekRank:1,
      monthRank:1,
    },
    {
      id: 4,
      bookName: "자살일기",
      bookWriter: "파블로다니엘",
      bookPoint: "시/에세이 카테고리 주간 4위",
      imgSrc: "./images/books/bookrank_poetry05.png",
      weekRank:3,
      monthRank:4,
    },
  ],

  liberal: [
    {
      id: 0,
      bookName: "단어가 품은 세계",
      bookWriter: "황선엽",
      bookPoint: "인문 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank01.png",
      weekRank:4,
      monthRank:3,
    },
    {
      id: 1,
      bookName: "구해줘",
      bookWriter: "기욤 뮈소 지음 / 윤미연 옮김",
      bookPoint: "소설 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank02.png",
      weekRank:1,
      monthRank:0,
    },
    {
      id: 2,
      bookName: "애 같은 말투 10분 만에 바꿔 드립니다",
      bookWriter: "김채린",
      bookPoint: "자기계발 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank03.png",
      weekRank:3,
      monthRank:2,
    },
    {
      id: 3,
      bookName: "싯다르타",
      bookWriter: "헤르만 헤세 지음 / 박병덕 옮김",
      bookPoint: "소설 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank04.png",
      weekRank:2,
      monthRank:4,
    },
    {
      id: 4,
      bookName: "지적 대화를 위한 넓고 얕은 지식 무한",
      bookWriter: "채사장",
      bookPoint: "오디오북 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank05.png",
      weekRank:0,
      monthRank:1,
    },
  ],
  hobby: [
    {
      id: 0,
      bookName: "파과",
      bookWriter: "구병모",
      bookPoint: "소설 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_novel01.png",
      weekRank:0,
      monthRank:0,
    },
    {
      id: 1,
      bookName: "폴링 인 폴",
      bookWriter: "백수련",
      bookPoint: "소설 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank_novel02.png",
      weekRank:2,
      monthRank:1,
    },
    {
      id: 2,
      bookName: "급류",
      bookWriter: "정대건",
      bookPoint: "소설 카테고리 주간 3위",
      imgSrc: "./images/books/bookrank_novel03.png",
      weekRank:1,
      monthRank:2,
    },
    {
      id: 3,
      bookName: "스토너",
      bookWriter: "존윌리엄스 지음, 김승옥 옮김",
      bookPoint: "소설 카테고리 주간 4위",
      imgSrc: "./images/books/bookrank_novel04.png",
      weekRank:4,
      monthRank:4,
    },
    {
      id: 4,
      bookName: "메스를 든 사냥꾼",
      bookWriter: "최이도",
      bookPoint: "소설 카테고리 주간 5위",
      imgSrc: "./images/books/bookrank_novel05.png",
      weekRank:3,
      monthRank:3,
    },
  ],
  child: [
    {
      id: 0,
      bookName: "따박따박 경제상식 [ETF 첫걸음]",
      bookWriter: "밀리의서재 편집부",
      bookPoint: "따끈따끈 인기있는 신간을 확인해보세요",
      imgSrc: "./images/books/bookrank_economy01.png",
      weekRank:0,
      monthRank:1,
    },
    {
      id: 1,
      bookName: "단 3개의 미국 ETF로 은퇴하라",
      bookWriter: "김지훈(포메뽀꼬)",
      bookPoint: "경제경영 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_economy02.png",
      weekRank:2,
      monthRank:4,
    },
    {
      id: 2,
      bookName: "따박따박 경제상식 [ETF 실전]",
      bookWriter: "밀리의서재 편집부",
      bookPoint: "따끈따끈 인기있는 신간을 확인해보세요",
      imgSrc: "./images/books/bookrank_economy03.png",
      weekRank:1,
      monthRank:0,
    },
    {
      id: 3,
      bookName: "결핍은 우리를 어떻게 변화시키는가",
      bookWriter: "센딜 멀레이너선, 엘다 샤퍼 지음 / 이경식 옮김",
      bookPoint: "경제경영 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank_economy04.png",
      weekRank:3,
      monthRank:2,
    },
    {
      id: 4,
      bookName: "조용한 퇴사",
      bookWriter: "이호건",
      bookPoint: "경제경영 카테고리 주간 3위",
      imgSrc: "./images/books/bookrank_economy05.png",
      weekRank:4,
      monthRank:3,
    },
  ],
  magazine: [
    {
      id: 0,
      bookName: "생각하는 대로 그렇게 된다",
      bookWriter: "제임스 앨런",
      bookPoint: "오디오북 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_self01.png",
      weekRank:3,
      monthRank:2,
    },
    {
      id: 1,
      bookName: "업무시간을 반으로 줄이느 챗GPT 글쓰기",
      bookWriter: "정태일",
      bookPoint: "따끈따끈 인기있는 신간을 확인해보세요",
      imgSrc: "./images/books/bookrank_self02.png",
      weekRank:0,
      monthRank:3,
    },
    {
      id: 2,
      bookName: "호감 가는 사람은 말투가 다르다",
      bookWriter: "박근일",
      bookPoint: "자기계발 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_self03.png",
      weekRank:1,
      monthRank:0,
    },
    {
      id: 3,
      bookName: "살아갈 날들을 위한 괴테의 시",
      bookWriter: "김종원",
      bookPoint: "자기계발 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank_self04.png",
      weekRank:4,
      monthRank:1,
    },
    {
      id: 4,
      bookName: "사랑받는 이기주의자",
      bookWriter: "박코",
      bookPoint: "자기계발 카테고리 주간 3위",
      imgSrc: "./images/books/bookrank_self05.png",
      weekRank:3,
      monthRank:4,
    },
  ],
  fantasy: [
    {
      id: 0,
      bookName: "고독한 미식가",
      bookWriter: "다니구치 지로 지음 / 구스미 마사유키 원작 / 박정임 옮김",
      bookPoint: "만화 카테고리 주간 1위",
      imgSrc: "./images/books/bookrank_poetry01.png",
      weekRank:2,
      monthRank:3,
    },
    {
      id: 1,
      bookName: "하늘을 봐, 바람이 불고 있어",
      bookWriter: "고윤(페이서스코리아)",
      bookPoint: "따끈따끈 인기있는 신간을 확인해보세요",
      imgSrc: "./images/books/bookrank_poetry02.png",
      weekRank:0,
      monthRank:0,
    },
    {
      id: 2,
      bookName: "어른의 행복은 조용하다",
      bookWriter: "태수",
      bookPoint: "시/에세이 카테고리 주간 2위",
      imgSrc: "./images/books/bookrank_poetry03.png",
      weekRank:4,
      monthRank:2,
    },
    {
      id: 3,
      bookName: "사랑읭 정의는 고양이",
      bookWriter: "임현우",
      bookPoint: "시/에세이 카테고리 주간 3위",
      imgSrc: "./images/books/bookrank_poetry04.png",
      weekRank:1,
      monthRank:1,
    },
    {
      id: 4,
      bookName: "자살일기",
      bookWriter: "파블로다니엘",
      bookPoint: "시/에세이 카테고리 주간 4위",
      imgSrc: "./images/books/bookrank_poetry05.png",
      weekRank:3,
      monthRank:4,
    },
  ],
};
