export let feedManager_book = {
  post: [
    {
      id: 0,
      imgSrc : "post_01",
      users_name: "푸른 미리내",
      book_name: "배틀 아일랜드",
      book_desc: "만약 무인도에 가져 갈 물건 갯수가 3개 뿐이라면 무엇을 선택해야 할까?",
    },
    {
      id: 1,
      imgSrc : "post_02",
      users_name: "Ssohyun",
      book_name: "마음 깊은 숨",
      book_desc: "짧은 단편이지만 여운이 많이 남았다. 같은 기억을 공유한다는 것은 어떤 의미일까.",
    },
    {
      id: 2,
      imgSrc : "post_03",
      users_name: "아로미",
      book_name: "생각을 모으는 사람",
      book_desc: "수줍음 많은 생각을 모아 가지런히 정리 해주고 흙 속에 정성껏 심어주면 각자 나름대로 모양의 꽃으로 ...",
    },
    {
      id: 3,
      imgSrc : "post_04",
      users_name: "다이어터 머그컵",
      book_name: "스토너",
      book_desc: "반전은 없었다. 순리대로, 원래의 모습대로, 그렇게 흘러가는대로. 안타까운 일도 있지만 눈물이 나지는 ...",
    },
    {
      id: 4,
      imgSrc : "post_05",
      users_name: "서림풀밭",
      book_name: "나무",
      book_desc: "나무의 모양은 희망이다. 희망의 숲에 아름다운 미래란오솔길이 만들어지고 그 숲길을 나무의 잎처럼 오롯 ...",
    },
    {
      id: 5,
      imgSrc : "post_06",
      users_name: "꿀넣은라떼",
      book_name: "궤도의 과학 허세",
      book_desc: "과학 미치광이이자 과학 밖에 모르는 과학에 진심인 과학자의 시선으로 바라 본 세상 이야기.",
    },
    {
      id: 6,
      imgSrc : "post_07",
      users_name: "정확한리뷰어",
      book_name: "AI 지배자",
      book_desc: "AI 특히 llm에 대한 질문 방법, 한글만 읽을 줄 안다면 가능한 프롬프트 엔지니어링을 통해 AI를 가장 잘 ...",
    },
    {
      id: 7,
      imgSrc : "post_08",
      users_name: "mkanalog_readers",
      book_name: "작가의 모든 것 : 백수린",
      book_desc: "작가의 생각이나 의도를 내 식으로 해석하는 것도 좋고, 이렇게 알 수 있어도 좋다.",
    },
  ],
  review: [
    {
      id: 0,
      imgSrc : "review_01",
      users_name: "다락방조이",
      book_name: "스토너",
      book_desc: "한 남자의 일대기를 통해 삶의 기쁨과 슬픔 허망함을 받아들이는 연습을 할 수 있는 책",
    },
    {
      id: 1,
      imgSrc : "review_02",
      users_name: "마음 편한 커피콩빵",
      book_name: "판례 법학방법론",
      book_desc: "법문과 법관, 그리고 법률해석의 방법 및 충돌 등 법에 대한 유익한 논의를 볼 수 있다.",
    },
    {
      id: 2,
      imgSrc : "review_03",
      users_name: "침대 밖이 싫은 순두부",
      book_name: "부모의 질문력",
      book_desc: "어떤 부모가 되어야할지 치열하게 고민하는 부모들에게 오히려 질문을 던지는 책.",
    },
    {
      id: 3,
      imgSrc : "review_04",
      users_name: "프렌들리 레이나",
      book_name: "어른의 행복은 조용하다",
      book_desc: "평범한 일상의 글인데 눈물 흘리며 보았습니다. 행복이 무엇인가를 다시 한번 정의해보았습니다.",
    },
    {
      id: 4,
      imgSrc : "review_05",
      users_name: "내사랑ZN",
      book_name: "수요일의 편지법론",
      book_desc: "긍정적으로 살고 싶어지는 책. 따뜻하고 마음에 위로가 된다. 나를 위해 수요일에 편지를 써보자~",
    },
    {
      id: 5,
      imgSrc : "review_06",
      users_name: "실버스타73",
      book_name: "내가 죽기 일주일 전",
      book_desc: "희완이의 생이 다 한 후가 궁금하다. 람우랑 희완이는 그 뒤에 어떻게 됐을까.",
    },
    {
      id: 6,
      imgSrc : "review_07",
      users_name: "밍쟁",
      book_name: "율의 시선",
      book_desc: "읽는내내 데미안 생각이 났다. 율의 성장이 좋았고 도해가 어디선가 훨훨 날기를 바란다.",
    },
    {
      id: 7,
      imgSrc : "review_08",
      users_name: "책읽는나연",
      book_name: "사랑의 정의는 고양이",
      book_desc: "정신없이 살아내다 우연히 추천도서에 떠있어서 읽기 시작했는데, 잠깐 세상이 멈춘 기분입니다.",
    },
  ],
  highlight: [
     {
      id: 0,
      imgSrc : "high_01",
      users_name: "Fox eating books",
      book_name: "하이데거의 존재와 시간 읽기",
      book_desc: "'도구적으로 존재하는 자연의 존재양식을 도외시할 경우에야 비로소 자연 그 자체가 순수한 눈앞의 존재...'",
    },
     {
      id: 1,
      imgSrc : "high_02",
      users_name: "기분조아",
      book_name: "불안할 땐 뇌과학",
      book_desc: "'도구적으로 존재하는 자연의 존재양식을 도외시할 경우에야 비로소 자연 그 자체가 순수한 눈앞의 존재...'",
    },
     {
      id: 2,
      imgSrc : "high_03",
      users_name: "쭌서재",
      book_name: "결핍은 우리를 어떻게 변화시키는가",
      book_desc: "'결핍의 심리에 초점을 맞출 경우 전혀 다른 해결책이 나온다. 동기부여나 교육, 당근이나 채찍이 아니라...'",
    },
     {
      id: 3,
      imgSrc : "high_04",
      users_name: "HoLo서기",
      book_name: "(프로이트의) 정신분석과 전쟁신경증",
      book_desc: "'따라서, 신경증은 프랑스 학파에서 주장하는 것처럼 질병이나 우연한 사고가 아닙니다.'",
    },
     {
      id: 4,
      imgSrc : "high_05",
      users_name: "라이프코치77",
      book_name: "사이토 히토리 1% 부자의 대화법",
      book_desc: "'밝은 말은 쓰면 쓸수록 더 많은 밝은 에너지를 뿜어냅니다. 기운을 한껏 높여주니 좋은 일이 꼬리에 꼬리...'",
    },
     {
      id: 5,
      imgSrc : "high_06",
      users_name: "잠재의식09",
      book_name: "루소의 에밀",
      book_desc: "'에밀의 신체와 정신이 충분히 성장했으므로 이제 나는 에밀이 기술과 지식을 쌓도록 도와줄 것입니다.'",
    },
     {
      id: 6,
      imgSrc : "high_07",
      users_name: "밝은 주인공",
      book_name: "단 3개의 미국 ETF로 은퇴하라",
      book_desc: "'당신도 혹시 오르기만을 기도하며 마음 졸이는 ‘투기’를 하고 있지는 않는가. 그렇다면 안정적으로...'",
    },
     {
      id: 7,
      imgSrc : "high_08",
      users_name: "강한 아티스트",
      book_name: "불안한 완벽주의자를 위한 책",
      book_desc: "'구체적이고, 측정 가능하고, 달성 가능하고, 의미 있으며, 시간 제한이 있는가? 그렇지 않다면 수정하고...'",
    },
  ],
  lifeBook: [
     {
      id: 0,
      imgSrc : "life_01",
      users_name: "낭만은",
      book_name: "사랑의 정의는 고양이",
      book_desc: "평소 고양이가 좋아서 읽었지만 생각보다 글이 너무 좋아서 놀라움",
    },
     {
      id: 1,
      imgSrc : "life_02",
      users_name: "좋은책만",
      book_name: "자살일기",
      book_desc: "진짜 믿고 읽으세요. 너무 좋아요",
    },
     {
      id: 2,
      imgSrc : "life_03",
      users_name: "문학의 서재",
      book_name: "귤이 달았던 날을 기억하세요?",
      book_desc: "최근 밀리에서 읽은 책 중 가장 좋았다.",
    },
     {
      id: 3,
      imgSrc : "life_04",
      users_name: "매일야옹",
      book_name: "우리 죽을 각오로 사랑할까요?",
      book_desc: "모두가 이런 사랑을 하고 싶지 않을까? 다들 꼭 읽어보면 좋은 책.",
    },
     {
      id: 4,
      imgSrc : "life_05",
      users_name: "책연구가z",
      book_name: "장마가 오면 내 생각을 할까요?",
      book_desc: "파블로다니엘의 책을 읽으면 모든 장면이 머릿속 영화처럼 상상된다. 섬세함에 늘 감탄한다.",
    },
     {
      id: 5,
      imgSrc : "life_06",
      users_name: "빵을 좋아하는 머그컵",
      book_name: "달에서 아침을",
      book_desc: "세상의 모든 곰들에게 읽어보기를 권합니다.",
    },
     {
      id: 6,
      imgSrc : "life_07",
      users_name: "Romantic Tough",
      book_name: "나는 어떻게 삶의 해답을 찾는가",
      book_desc: "왜 책을 읽어야 하는지 답을 제시하고, 그 단계별 방향도 제시해주는 책.",
    },
     {
      id: 7,
      imgSrc : "life_08",
      users_name: "새로 이사온 소보로빵",
      book_name: "급류",
      book_desc: "이 책은 내가 외면해온 감정과 마주하게 했다. 사랑이라는 이름 아래 감춰졌던 나의 치졸함을 꿰뚫으며...",
    },
  ],
};
