export let division = {
  holric: [
    {
      id: 0,
      bookName: "PLAN B 플랜 B",
      category: "경제경영 분야",
      completPer: 65,
      completTime: 95,
      completPer_Avg: 56,
      completTime_Avg: 130,
      completPer_than: "up",
      completTime_than: "down",
      bookCover_url: "book_holic1",
    },
    {
      id: 1,
      bookName: "낯선 여자가 매일 집에 온다",
      category: "에세이/시 분야",
      completPer: 78,
      completTime: 88,
      completPer_Avg: 55,
      completTime_Avg: 100,
      completPer_than: "up",
      completTime_than: "down",
      bookCover_url: "book_holic2",
    },
    {
      id: 2,
      bookName: "기밀의 유혹",
      category: "소설 분야",
      completPer: 74,
      completTime: 31,
      completPer_Avg: 66,
      completTime_Avg: 164,
      completPer_than: "up",
      completTime_than: "down",
      bookCover_url: "book_holic3",
    },
    {
      id: 3,
      bookName: "AI도 모르는 부의 비밀",
      category: "경제경영 분야",
      completPer: 71,
      completTime: 125,
      completPer_Avg: 56,
      completTime_Avg: 129,
      completPer_than: "up",
      completTime_than: "down",
      bookCover_url: "book_holic4",
    },
    {
      id: 4,
      bookName: "옆집의 경제학",
      category: "경제경영 분야",
      completPer: 70,
      completTime: 92,
      completPer_Avg: 56,
      completTime_Avg: 129,
      completPer_than: "up",
      completTime_than: "down",
      bookCover_url: "book_holic5",
    },
  ],
  milliePic: [
    {
      id: 0,
      bookName: "어느 물리학자의 비행",
      category: "소설 분야",
      completPer: 76,
      completTime: 289,
      completPer_Avg: 66,
      completTime_Avg: 164,
      completPer_than: "up",
      completTime_than: "up",
      bookCover_url: "book_pick1",
    },
    {
      id: 1,
      bookName: "나의 아메리카 생존기",
      category: "청소년 분야",
      completPer: 71,
      completTime: 120,
      completPer_Avg: 58,
      completTime_Avg: 80,
      completPer_than: "up",
      completTime_than: "up",
      bookCover_url: "book_pick2",
    },
    {
      id: 2,
      bookName: "치맥과 양아치",
      category: "에세이/시 분야",
      completPer: 67,
      completTime: 154,
      completPer_Avg: 55,
      completTime_Avg: 100,
      completPer_than: "up",
      completTime_than: "up",
      bookCover_url: "book_pick3",
    },
    {
      id: 3,
      bookName: "밤과 노래",
      category: "인문 분야",
      completPer: 59,
      completTime: 117,
      completPer_Avg: 52,
      completTime_Avg: 103,
      completPer_than: "up",
      completTime_than: "up",
      bookCover_url: "book_pick4",
    },
    {
      id: 4,
      bookName: "쉽게 믿는 자들의 민주주의",
      category: "사회 분야",
      completPer: 60,
      completTime: 197,
      completPer_Avg: 53,
      completTime_Avg: 111,
      completPer_than: "up",
      completTime_than: "up",
      bookCover_url: "book_pick5",
    },
  ],
  hidden: [
    {
      id: 0,
      bookName: "우리들의 비밀 온실",
      category: "소설 분야",
      completPer: 65,
      completTime: 130,
      completPer_Avg: 66,
      completTime_Avg: 164,
      completPer_than: "down",
      completTime_than: "down",
      bookCover_url: "book_hidden1",
    },
    {
      id: 1,
      bookName: "그날의 비밀",
      category: "소설 분야",
      completPer: 60,
      completTime: 163,
      completPer_Avg: 66,
      completTime_Avg: 164,
      completPer_than: "down",
      completTime_than: "down",
      bookCover_url: "book_hidden2",
    },
    {
      id: 2,
      bookName: "게이트",
      category: "소설 분야",
      completPer: 57,
      completTime: 150,
      completPer_Avg: 66,
      completTime_Avg: 164,
      completPer_than: "down",
      completTime_than: "down",
      bookCover_url: "book_hidden3",
    },
    {
      id: 3,
      bookName: "우정이 맘대로 되나요?",
      category: "청소년 분야",
      completPer: 55,
      completTime: 86,
      completPer_Avg: 58,
      completTime_Avg: 87,
      completPer_than: "down",
      completTime_than: "down",
      bookCover_url: "book_hidden4",
    },
    {
      id: 4,
      bookName: "인생독썰",
      category: "자기계발 분야",
      completPer: 53,
      completTime: 97,
      completPer_Avg: 53,
      completTime_Avg: 107,
      completPer_than: "down",
      completTime_than: "down",
      bookCover_url: "book_hidden5",
    },
  ],
  mania: [
    {
      id: 0,
      bookName: "무죄의 여름",
      category: "소설 분야",
      completPer: 61,
      completTime: 378,
      completPer_Avg: 66,
      completTime_Avg: 164,
      completPer_than: "down",
      completTime_than: "up",
      bookCover_url: "book_mania1",
    },
    {
      id: 1,
      bookName: "선택",
      category: "소설 분야",
      completPer: 55,
      completTime: 192,
      completPer_Avg: 66,
      completTime_Avg: 164,
      completPer_than: "down",
      completTime_than: "up",
      bookCover_url: "book_mania2",
    },
    {
      id: 2,
      bookName: "디피런트",
      category: "경제경영 분야",
      completPer: 51,
      completTime: 256,
      completPer_Avg: 56,
      completTime_Avg: 129,
      completPer_than: "down",
      completTime_than: "up",
      bookCover_url: "book_mania3",
    },
    {
      id: 3,
      bookName: "미움받는 식물들",
      category: "과학 분야",
      completPer: 49,
      completTime: 188,
      completPer_Avg: 53,
      completTime_Avg: 92,
      completPer_than: "down",
      completTime_than: "up",
      bookCover_url: "book_mania4",
    },
    {
      id: 4,
      bookName: "데이터 자본주의",
      category: "경제경영 분야",
      completPer: 41,
      completTime: 154,
      completPer_Avg: 56,
      completTime_Avg: 129,
      completPer_than: "down",
      completTime_than: "up",
      bookCover_url: "book_mania5",
    },
  ],
};
